import Header from "@/components/Header/Header";
import RootContainer from "@/components/RootContainer";
import type { Metadata } from "next";
import "../../public/reset.css";
import { color } from "@/styles/color";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body style={{ background: color.white }}>
        <RootContainer>
          <Header />
          {children}
        </RootContainer>
      </body>
    </html>
  );
}
