import Header from "@/components/Header/Header";
import RootContainer from "@/components/RootContainer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <RootContainer>{children}</RootContainer>
      </body>
    </html>
  );
}
